magazine/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from articles.views import index, retrieve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('<int:id>/', retrieve, name='Retrieve'),
    path('', index)
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articles/models.py
from django.db import models
from django.contrib.auth.models import User


class Article(models.Model):
    title = models.CharField(max_length=128)
    description = models.TextField()
    is_active = models.BooleanField()
    image = models.ImageField(upload_to="article-images")
    related_user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

class Comment(models.Model):
    content = models.TextField()
    related_article = models.ForeignKey(Article, on_delete=models.CASCADE)
    related_user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.content

class ArticleImage(models.Model):
    image = models.ImageField(upload_to='gallery-images')
    related_article = models.ForeignKey(Article, on_delete=models.CASCADE)
    related_user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.image}'

articles/forms.py
from django.forms import ModelForm
from .models import Article, Comment

class ArticleForm(ModelForm):
    class Meta:
        model = Article
        fields = '__all__'
    
    def __init__(self, *args, **kwargs):
        super(ArticleForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field_name != 'is_active':
                field.widget.attrs['class'] = 'form-control'

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = '__all__'

articles/views.py
from django.shortcuts import render
from articles.models import Article
from .forms import ArticleForm, CommentForm


def index(request):
    if request.method == "POST":
        form = ArticleForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
    else:
        form = ArticleForm()
    # articles = Article.objects.all()
    articles = Article.objects.filter(is_active=True)
    context = {
        'articles': articles,
        'form': form
    }
    return render(request, 'index.html', context)

def retrieve(request, id):
    article = Article.objects.get(id=id)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            form.save()
    comment_form = CommentForm()
    context = {
        'article': article,
        'comment_form': comment_form
    }
    return render(request, 'retrieve.html', context)

articles/templates/index.html
{% extends 'layout.html' %}


{% block content %}
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form}}
    <input type="submit" value="Submit" class="btn btn-primary mt-3" />
</form>
<h1>Articles List</h1>
<hr>
{% for article in articles %}
    {% if article.image %}
        <img src="{{article.image.url}}" style="width:300px">
    {% endif %}
    <a href="{% url 'Retrieve' id=article.id %}"><h2>{{article.title}}</h2></a>
    <p>{{article.description}}</p>
    <hr>
{% endfor %}
{% endblock %}

articles/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Website Layout</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
</head>
<body>
    <div class="container">
        {% block content %}{% endblock %}
    </div>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

articles/templates/retrieve.html
{% extends 'layout.html' %}

{% block content %}
{% if article.image %}
    <img src="{{article.image.url}}" style="width:500px">
{% endif %}
<h1>{{article.title}}</h1>
<p>{{article.description}}</p>

{% for article_image in article.articleimage_set.all %}
<img src="{{article_image.image.url}}" style="width:256px">
{% endfor %}

{% for comment in article.comment_set.all %}
<h5>{{comment.related_user.first_name}} {{comment.related_user.last_name}}</h5>
<p>{{comment.content}}</p>
{% endfor %}

<form action="" method="POST">
    {% csrf_token %}
    <input type="hidden" name="related_article" value="{{article.id}}">
    <textarea name="content" class="form-control mb-3" placeholder="Comment ..."></textarea>
    <input type="hidden" name="related_user" value="1">
    <input type="submit" value="Submit" class="btn btn-primary">
</form>
{% endblock %}